"""add_session_ledger_table

Revision ID: 2243ee8e39aa
Revises: 8798134dd62e
Create Date: 2026-01-16 11:05:04.960460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2243ee8e39aa'
down_revision: Union[str, None] = '8798134dd62e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

