"""add polygon and ai_label to clusters

Revision ID: 8798134dd62e
Revises: 
Create Date: 2026-01-14 20:37:36.397698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8798134dd62e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clusters', sa.Column('polygon', sa.JSON(), nullable=True))
    op.add_column('clusters', sa.Column('ai_label', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clusters', 'ai_label')
    op.drop_column('clusters', 'polygon')
    # ### end Alembic commands ###

